name: analytics-api => stage
on:
  push:
    branches:    
      - 'stage'
    paths:
      - "apps/analytics-api/**"
      - ".github/workflows/analytics-api-stage.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '-A apps/analytics-api/vercel.json' #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.BACKEND_PROJECT_ID}} #Required 
          github-token: ${{ secrets.CI_TOKEN }}
          alias-domains: | #Optional
            backend-stage.templedao.link
