name: analytics-api => prod
on:
  push:
    branches:    
      - 'main'
    paths:
      - "apps/analytics-api/**"
      - ".github/workflows/analytics-api-prod.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod -A apps/analytics-api/vercel.json' #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  #Required
          vercel-project-id: ${{ secrets.BACKEND_PROJECT_ID }} #Required 
          github-token: ${{ secrets.CI_TOKEN }}
          github-comment: false
          scope: ${{ secrets.VERCEL_ORG_ID }}
          alias-domains: | #Optional
            backend.templedao.link
