name: backend => prod
on:
  push:
    branches:    
      - 'main'
    paths:
      - "apps/backend/**"
      - ".github/workflows/backend-prod.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod -A apps/backend/vercel.json' #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.BACKEND_PROJECT_ID}} #Required 
          github-token: ${{ secrets.CI_TOKEN }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          alias-domains: | #Optional
            backend.templedao.link
